language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
 - pip install python-coveralls
 - pip install 'coverage<4'
# command to run tests
script:
  - python setup.py test
  - coverage run setup.py test
after_success:
    - coveralls